# Generated by Django 6.1 on 2026-09-04 02:44

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The field is saved news category', max_length=255, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='The field is saved news title', max_length=255, verbose_name='News title')),
                ('description', models.TextField(help_text='The field is saved news description', verbose_name='News description')),
                ('image', models.ImageField(blank=True, help_text='The field is saved news image', null=True, upload_to='news/', verbose_name='News Image')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('category', models.ForeignKey(help_text='The field is saved news category', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.newscategory', verbose_name='News category')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
