# Generated by Django 6.1 on 2026-09-04 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='The field is saved blog title', max_length=255, verbose_name='Blog title')),
                ('description', models.TextField(help_text='The field is saved blog description', verbose_name='Blog description')),
                ('image', models.ImageField(blank=True, help_text='The field is saved blog image', null=True, upload_to='blog/', verbose_name='Blog Image')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The field is saved blog category', max_length=255, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogCategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(blank=True, help_text='The filed is saved blog.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blog', verbose_name='Blog')),
                ('blog_category', models.ForeignKey(blank=True, help_text='The filed is saved blog category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Blog Category')),
            ],
            options={
                'verbose_name': 'Blog Category Blog',
                'verbose_name_plural': 'Blog Category Blogs',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(help_text='The filed is saved blog category.', through='blog.BlogCategoryBlog', to='blog.blogcategory', verbose_name='Blog Category'),
        ),
    ]
